const playerNameGrammar = {
"origin": "#firstName# #lastName#",
"firstName": ["Seabright", "Max", "Nic", "Alex", "Mel", "Jason", "Cat", "Kate", "Jacob", "Jacan", "Aaron", "Telephone", "Katie", "Barrett", "Jasmine", "Sam", "Stella", "Stacey", "Kyle", "Asiiah", "Dani", "Erica", "Tammy", "Shawn", "Ahab",
"Anj",
"Bella",
"Bob",
"Clementine",
"Demeter",
"Duncan",
"Emmett",
"Esther",
"Fred",
"George",
"Georgina",
"Geoff",
"Greg",
"Harwood",
"Harrow",
"Ichabod",
"Ivan",
"Ingrid",
"Insultia",
"Jeff",
"Kirk",
"Kurt",
"Karina",
"Lavender",
"Markus",
"Norbert",
"Nance",
"Olivia",
"Oliver",
"Olivetti",
"Percy",
"Pangaea",
"Penny",
"Quinn",
"Quoththeraven",
"Rob",
"Rigel",
"Serena",
"Tom",
"Turpentine",
"Terrence",
"Tercy",
"Ursula",
"Ulysses",
"Vince",
"Victor",
"Victoria",
"Valerie",
"Vanessa",
"Walt",
"Willamette",
"Win",
"Xavier",
"Yancy",
"Ying",
"Zefram",
"Ali",
"Bethny",
"Cara",
"Chance",
"Chester",
"Chuck",
"Falchion",
"Felienne",
"Faysal",
"Gensym",
"Jack",
"January",
"Julie",
"Jules",
"Keith",
"Kendall",
"Kelvin",
"Kimball",
"Lara",
"Lee",
"Lora",
"Lucifer",
"Malefactor",
"Matthew",
"Mark",
"Marcia",
"Miles",
"Narrow",
"Olgun",
"Phoebe",
"Pierre",
"Pyotr",
"Quelsey",
"Quincy",
"River",
"Rouen",
"Ruslan",
"Sage",
"Seldom",
"Sherman",
"Sorrel",
"Vivian",
"Wake",
"Wastrel",
"Wendell",
"Zacharias"],

"lastName": ["Camerata", "Kreminski", "Jessica", "Phoneme", "Stigmata", "Pattern", "Wolfenstein", "Short", "Wyeth", "Bones", "Tooth", "Fysher", "Lancaster", "Montgimery", "Montgomery", "Aaronson",
"Bannister",
"Bilge",
"Cavalcade",
"Douglas",
"Devereaux",
"Diesel",
"Englestein",
"Everest",
"Firth",
"Ford",
"Fulsom",
"Georgewardly",
"Grant",
"Hingeman",
"Ifferfehl",
"Ippolito",
"Jefferson",
"Ko",
"Kristofferson",
"Lawrence",
"Livermore",
"Mange",
"Malaprop",
"Meese",
"Norwood",
"Naw",
"Nevermore",
"O'Shaughnessy",
"Purcell",
"Questceque",
"Rackham",
"Sheen",
"Sleigh",
"To",
"Usual",
"Vance",
"Wenceslas",
"Wong",
"Xi",
"Yi",
"Zee",
"Adams",
"Augenbrecht",
"Balustrade",
"Boniface",
"Bellevue",
"Capstan",
"Cherny",
"Corbusier",
"Dameris",
"Delaunay",
"Duchamp",
"Dufort",
"Dubnov",
"Gaulein",
"Harkness",
"Henge",
"Huang",
"Hicks",
"Hickerson",
"Karst",
"Leyden",
"Marriott",
"Mayoral",
"McQuade",
"Mirkowski",
"Perdedor",
"Scoresby",
"Shrike",
"Specht",
"Stover",
"Strike",
"Substance",
"Taber",
"Tao",
"Thorn",
"Tulle",
"van der Decken",
"Vestige",
"Wallace",
"Young"]
}

function createRandomPlayer() {
    // const personality = {
        //     diligence: 0.019,
        //     fear: 0.0,
        //     distractibility: 0.05,
        //     teeth: 32,
        //     twitchiness: 0.41,
        //     edge: 0.9,
        //     areodynamics: 0.51,
        //     gumption: 0.5,
        //     grit: 0.5
        // };

    const personality = {
            diligence: Phaser.Math.FloatBetween(0.0, 1.0),
            fear: Phaser.Math.FloatBetween(0.0, 0.4),
            distractibility: Phaser.Math.FloatBetween(0.0, 1.0),
            teeth: 32,
            twitchiness: Phaser.Math.FloatBetween(0.0, 1.0),
            edge: Phaser.Math.FloatBetween(0.0, 1.0),
            areodynamics: Phaser.Math.FloatBetween(0.0, 1.0),
            gumption: Phaser.Math.FloatBetween(0.0, 1.0),
            grit: Phaser.Math.FloatBetween(0.0, 1.0),
            fuse: Phaser.Math.FloatBetween(0.0, 1.0)
        };

    return {
    	"name": tracery.createGrammar(playerNameGrammar).flatten("#origin#"),
    	"personality": personality
    }
}

const teamFancyNameList = ["Akron Aliens 👽", "Saskatoon Steelmen 🦾", "Fremont Foxes🦊", "Nacogdoches No 🙅‍♀️", "Eureka Euphemisms 🙊", "Toronto Teeth 🦷", "West Lafayette Wildebeests 🦬", "Kalamazoo Koalas 🐨", "Milwaukee Marxists 🥸", "Hadleyburg Haze 😶‍🌫️"];
const teamNameList = ["Akron Aliens", "Saskatoon Steelmen", "Fremont Foxes", "Nacogdoches No", "Eureka Euphemisms", "Toronto Teeth", "West Lafayette Wildebeests", "Kalamazoo Koalas", "Milwaukee Marxists", "Hadleyburg Haze"];

function CreateTeam(teamName, fancyName) {
	const playerList = [];
	const teamSize = 5;

	const numPlayers = teamSize;
    for(let i = 0; i < numPlayers; i++) {
    	const player = createRandomPlayer();
    	playerList.push(player);
    }
    return {
    	"roster": playerList,
    	"name": teamName,
    	"fancyName": fancyName
    }
}

const teamList = [];
for(let i = 0; i < teamNameList.length; i++) {
    let name = teamNameList[i];
	teamList.push(CreateTeam(name, teamFancyNameList[i]));
}
for(team of teamList) {
	console.log(team);
}